[package]
name = "bin-mean"
version = "0.1.0"
edition = "2021"

[dependencies]

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
undocumented_unsafe_blocks = "forbid"
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -2 }
